#!/usr/bin/env python3
"""
First-time setup — opens a browser for each integration and saves credentials to .env.

Usage: python bootstrap.py
Re-run at any time to add or update a service.
"""
import os
import sys
import time
import webbrowser
from pathlib import Path

ENV_FILE = Path(".env")
CREDS_FILE = Path("credentials.json")
TOKEN_FILE = Path("token.json")

GOOGLE_SCOPES = [
    "https://www.googleapis.com/auth/gmail.readonly",
    "https://www.googleapis.com/auth/calendar.readonly",
]


# ── helpers ──────────────────────────────────────────────────────────────────

def load_env() -> dict:
    env = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                env[k.strip()] = v.strip()
    return env


def save_env(env: dict):
    lines = ["# Generated by bootstrap.py — edit freely", ""]
    for k, v in env.items():
        lines.append(f"{k}={v}")
    ENV_FILE.write_text("\n".join(lines) + "\n")
    print(f"  Saved to .env")


def ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    val = input(f"  {prompt}{suffix}: ").strip()
    return val or default


def section(title: str):
    print(f"\n── {title} {'─' * max(0, 48 - len(title))}")


def ok(msg: str):
    print(f"  {msg} ✓")


def skip(msg: str):
    print(f"  {msg}")


def open_url(url: str):
    """Open a URL in the browser and always print it — in case the wrong account opens."""
    print(f"  Opening: {url}")
    webbrowser.open(url)


# ── steps ────────────────────────────────────────────────────────────────────

def setup_vault(env: dict):
    section("Obsidian Vault")
    default = env.get("VAULT_PATH", str(Path.home() / "Documents" / "Obsidian Vault"))
    val = ask("Vault path", default)
    vault = Path(val)
    if not vault.exists():
        print(f"  Warning: path doesn't exist yet — that's fine if you'll create it later.")
    env["VAULT_PATH"] = str(vault)
    env.setdefault("DAILY_FOLDER", "Daily")
    ok("Vault configured")


def _ensure_google_apis_enabled():
    """Open the enable pages for Gmail and Calendar APIs, wait for confirmation."""
    # Detect project ID from credentials.json if available
    project_id = ""
    if CREDS_FILE.exists():
        try:
            import json
            data = json.loads(CREDS_FILE.read_text())
            project_id = (
                data.get("installed", data.get("web", {})).get("project_id", "")
            )
        except Exception:
            pass

    base = f"?project={project_id}" if project_id else ""
    gmail_url = f"https://console.cloud.google.com/apis/library/gmail.googleapis.com{base}"
    cal_url = f"https://console.cloud.google.com/apis/library/calendar-json.googleapis.com{base}"

    print()
    print("  Enabling Gmail and Google Calendar APIs (required).")
    print("  Opening both API pages — click 'Enable' on each if not already enabled.")
    print(f"  If the browser opens the wrong account, use these links directly:")
    print(f"    Gmail API:    {gmail_url}")
    print(f"    Calendar API: {cal_url}")
    time.sleep(2)
    open_url(gmail_url)
    time.sleep(1)
    open_url(cal_url)
    print()
    input("  Press Enter once you've enabled both APIs (takes ~30 seconds to propagate)...")


def setup_google(env: dict):
    section("Google — Gmail + Calendar")

    if TOKEN_FILE.exists():
        ok("Already authenticated (token.json found)")
        _ensure_google_apis_enabled()
        env.setdefault("GOOGLE_CREDENTIALS_FILE", "credentials.json")
        env.setdefault("GOOGLE_TOKEN_FILE", "token.json")
        return

    # Step 1 — get credentials.json
    if not CREDS_FILE.exists():
        print("  Step 1: Create OAuth credentials in Google Cloud Console.")
        print("  Opening browser in 2 seconds...\n")
        time.sleep(2)
        open_url("https://console.cloud.google.com/apis/credentials")
        print("  Do this in the browser:")
        print("   1. Select or create a project (top-left dropdown)")
        print("   2. Click '+ Create Credentials' → 'OAuth client ID'")
        print("      (if prompted to configure consent screen first, do that — External, test mode is fine)")
        print("   3. Application type: Desktop app → Create")
        print("   4. Click Download JSON → rename the file to 'credentials.json'")
        print(f"   5. Move it to: {Path.cwd()}")
        print()

        # Poll up to 5 minutes for the file to appear
        print("  Waiting for credentials.json to appear in this folder", end="", flush=True)
        for _ in range(300):
            if CREDS_FILE.exists():
                print(" ✓")
                break
            print(".", end="", flush=True)
            time.sleep(1)
        else:
            print(f"\n  Timed out. Re-run bootstrap.py once you have credentials.json.\n")
            return

    _ensure_google_apis_enabled()

    # Step 2 — OAuth browser flow
    print("\n  Step 2: Sign in with Google (opening browser)...")
    time.sleep(1)
    try:
        from google_auth_oauthlib.flow import InstalledAppFlow
        from googleapiclient.discovery import build

        flow = InstalledAppFlow.from_client_secrets_file(str(CREDS_FILE), GOOGLE_SCOPES)
        creds = flow.run_local_server(port=0, access_type="offline", prompt="consent")
        TOKEN_FILE.write_text(creds.to_json())

        # Confirm by fetching email address
        service = build("gmail", "v1", credentials=creds)
        profile = service.users().getProfile(userId="me").execute()
        email = profile.get("emailAddress", "unknown")
        ok(f"Authenticated as {email}")

    except Exception as e:
        print(f"  Google auth failed: {e}")
        print("  Re-run bootstrap.py to try again.")
        return

    env["GOOGLE_CREDENTIALS_FILE"] = "credentials.json"
    env["GOOGLE_TOKEN_FILE"] = "token.json"


def setup_notion(env: dict):
    section("Notion")

    if env.get("NOTION_API_KEY"):
        ok("Already configured")
        return

    print("  Opening Notion integrations page in 2 seconds...")
    time.sleep(2)
    open_url("https://www.notion.so/my-integrations")
    print()
    print("  In the browser:")
    print("   1. Click '+ New integration'")
    print("   2. Give it any name (e.g. todos-with-obsidian)")
    print("   3. Click Submit → copy the 'Internal Integration Secret'")
    print()
    print("  Then share any pages or databases you want included:")
    print("   Open the page/database in Notion → ··· menu → Add connections → select your integration")
    print()

    key = ask("Paste your Notion integration secret (starts with secret_)")
    if not key:
        skip("Skipped — re-run bootstrap.py to add Notion later.")
        return

    env["NOTION_API_KEY"] = key
    ok("Configured — all pages/databases shared with the integration will be included automatically")



def setup_anthropic(env: dict):
    section("Anthropic — Claude chat")

    if env.get("ANTHROPIC_API_KEY"):
        ok("Already configured")
        return

    print("  Opening Anthropic console in 2 seconds...")
    time.sleep(2)
    open_url("https://console.anthropic.com/settings/keys")
    print()
    key = ask("Paste your Anthropic API key (or press Enter to skip)")
    if key:
        env["ANTHROPIC_API_KEY"] = key
        env.setdefault("ANTHROPIC_MODEL", "claude-opus-4-5")
        ok("Configured")
    else:
        skip("Skipped — chat won't work without this. Re-run bootstrap.py to add it later.")


# ── main ─────────────────────────────────────────────────────────────────────

def main():
    print()
    print("  todos-with-obsidian — setup")
    print("  ─────────────────────────────────────────────────")
    print("  This opens a browser for each service you want to connect.")
    print("  All credentials are saved locally to .env — never shared.")
    print("  Re-run at any time to add or update a service.")

    env = load_env()

    setup_vault(env)
    setup_google(env)
    setup_notion(env)

    save_env(env)

    print()
    print("  ─────────────────────────────────────────────────")
    print("  Done! Try it:")
    print()
    print("    python main.py daily    # generate today's Obsidian note")
    print()
    print("  For AI assistance, open Claude Code and ask about your vault.")
    print("  It can read your daily notes and Obsidian files directly.")
    print()


if __name__ == "__main__":
    main()
